apiVersion: apps/v1
kind: Deployment
metadata:
  name: spa-sample
  labels:
    app: spa-sample
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: spa-sample
  template:
    metadata:
      labels:
        app: spa-sample
    spec:
      containers:
        - name: spa
          image: kogayushi/k8s-spa-sample-app:0.0.1-SNAPSHOT
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: 25m
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
